name: Update.passwall-packages-xiao
on: 
  repository_dispatch:
  workflow_dispatch:

# 定时触发编译
  schedule:
    - cron: 0 23 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    - name: Set git
      run : |
        git config --global user.email "194788255+Jaykwok2999@users.noreply.github.com"
        git config --global user.name "Jaykwok2999"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 0  
        
    - name: packages
      run: |

        rm -rf ./dns2socks
        rm -rf ./geoview
        rm -rf ./hysteria
        rm -rf ./ipt2socks
        rm -rf ./microsocks
        rm -rf ./naiveproxy
        rm -rf ./pdnsd-alt
        rm -rf ./shadow-tls
        rm -rf ./shadowsocks-rust
        rm -rf ./shadowsocksr-libev
        rm -rf ./simple-obfs
        rm -rf ./sing-box
        rm -rf ./tcping
        rm -rf ./trojan-plus
        rm -rf ./tuic-client
        rm -rf ./v2ray-geodata
        rm -rf ./v2ray-plugin
        rm -rf ./xray-core
        rm -rf ./xray-plugin
        
        
         
        git clone https://github.com/xiaorouji/openwrt-passwall-packages.git ./tmp
        mv ./tmp/* ./
        rm -rf ./tmp
        rm -rf ./chinadns-ng
        
    - name: Apply
      run: |
        Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🛸" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        for pkg in $(git diff-tree --no-commit-id --name-only HEAD); do
          if [ "$(grep "PKG_RELEASE" $pkg/Makefile)" ]; then
            sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=$(git rev-list --count main $pkg)/" $pkg/Makefile || true
          fi
        done
        git reset --soft HEAD^
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f
