name: Update.passwall-packages
on:
  repository_dispatch:
  workflow_dispatch:
    schedule:
    - cron: "0 */4 * * *"
env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    - name: Set git
      run : |
        git config --global user.email "194788255+Jaykwok2999@users.noreply.github.com"
        git config --global user.name "Jaykwok2999"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 0  
        
    - name: Update
      run: |

        rm -rf ./brook
        rm -rf ./chinadns-ng
        rm -rf ./dns2socks
        rm -rf ./dns2socks-rust
        rm -rf ./dns2tcp
        rm -rf ./geoview
        rm -rf ./gn
        rm -rf ./hysteria
        rm -rf ./ipt2socks
        rm -rf ./microsocks
        rm -rf ./naiveproxy
        rm -rf ./pdnsd-alt
        rm -rf ./redsocks2
        rm -rf ./shadow-tls
        rm -rf ./shadowsocks-rust
        rm -rf ./shadowsocksr-libev
        rm -rf ./simple-obfs
        rm -rf ./sing-box
        rm -rf ./ssocks
        rm -rf ./tcping
        rm -rf ./trojan-go
        rm -rf ./trojan-plus
        rm -rf ./trojan
        rm -rf ./tuic-client
        rm -rf ./v2ray-core
        rm -rf ./v2ray-geodata
        rm -rf ./v2ray-geoview
        rm -rf ./v2ray-plugin
        rm -rf ./v2raya
        rm -rf ./xray-core
        rm -rf ./xray-plugin
        
        
         
        git clone https://github.com/kenzok8/small.git ./tmp
        mv ./tmp/* ./
        rm -rf ./tmp
        rm -rf ./lua-neturl
        rm -rf ./luci-app-bypass
        rm -rf ./luci-app-fchomo
        rm -rf ./luci-app-homeproxy
        rm -rf ./luci-app-mosdns
        rm -rf ./luci-app-nikki
        rm -rf ./luci-app-openclash
        rm -rf ./luci-app-passwall
        rm -rf ./luci-app-momo
        rm -rf ./luci-app-passwall2
        rm -rf ./luci-app-ssr-plus
        rm -rf ./momo
        rm -rf ./mihomo
        rm -rf ./mosdns
        rm -rf ./nikki
        rm -rf ./v2dat
        rm -rf ./LICENSE
        rm -rf ./README.md
        
    - name: Apply
      run: |
        Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🛸" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        for pkg in $(git diff-tree --no-commit-id --name-only HEAD); do
          if [ "$(grep "PKG_RELEASE" $pkg/Makefile)" ]; then
            sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=$(git rev-list --count main $pkg)/" $pkg/Makefile || true
          fi
        done
        git reset --soft HEAD^
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f
